### ISSUE TITLE
Rework of entrypoint.sh broke imapfilter

### ISSUE THREAD

**Issue by Shuro** [ntnn/docker-imapfilter#55]
Hi there,

I'm using the docker container to filter my mails since a long time, but after updating the container this week it doesn't work anymore. I'm using a folder as source of the imapfilter config.

Docker compose config:
```
  imapfilter-work:
    image: ntnn/imapfilter
    restart: always
    volumes:
      - ./imapfilter-work:/imapfilter-work
    environment:
      IMAPFILTER_CONFIG_BASE: /imapfilter-work
      IMAPFILTER_CONFIG: config.lua
```

Output running the container:
```
 shuro@mainframe  ~/services  docker compose up imapfilter-work
[+] Running 1/1
 ✔ Container services-imapfilter-work-1  Created                                                               0.0s
Attaching to imapfilter-work-1
imapfilter-work-1  | cat: can't open '': No such file or directory
imapfilter-work-1  | cat: can't open '': No such file or directory
imapfilter-work-1  | Config file 'config.lua' does not exist
imapfilter-work-1 exited with code 0
```

Some output trying to debug it:
```
shuro@mainframe  ~/services  docker compose run -it --entrypoint /bin/sh imapfilter-work
/ $ sh -x ./entrypoint.sh
+ config_target_prefix=/opt/imapfilter/config
+ config_in_vcs
+ vcs_token
+ '[' -n  ]
+ cat
cat: can't open '': No such file or directory
+ '[' -n  ]
+ config_target=config.lua
+ imapfilter_pid=
+ pull_config
+ config_in_vcs
+ vcs_token
+ '[' -n  ]
+ cat
cat: can't open '': No such file or directory
+ '[' -n  ]
+ return
+ '[' '!' -f config.lua ]
+ printf 'Config file '"'"'%s'"'"' does not exist\n' config.lua
Config file 'config.lua' does not exist
+ exit 1
```
